In [78]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import *
from sklearn.model_selection import *
from sklearn.ensemble import *
from sklearn.tree import *
from sklearn.linear_model import *
from sklearn.neighbors import *
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer

In [79]:
data = pd.read_csv('./Reviews.csv')

In [80]:
data.head()

Id   ProductId          UserId                      ProfileName  \
0   1  B001E4KFG0  A3SGXH7AUHU8GW                       delmartian   
1   2  B00813GRG4  A1D87F6ZCVE5NK                           dll pa   
2   3  B000LQOCH0   ABXLMWJIXXAIN  Natalia Corres "Natalia Corres"   
3   4  B000UA0QIQ  A395BORC6FGVXV                             Karl   
4   5  B006K2ZZ7K  A1UQRSCLF8GW1T    Michael D. Bigham "M. Wassir"   

   HelpfulnessNumerator  HelpfulnessDenominator  Score        Time  \
0                     1                       1      5  1303862400   
1                     0                       0      1  1346976000   
2                     1                       1      4  1219017600   
3                     3                       3      2  1307923200   
4                     0                       0      5  1350777600   

                 Summary                                               Text  
0  Good Quality Dog Food  I have bought several of the Vitality canned d...  
1      Not as Advertised  Product arrived labeled as Jumbo Salted Peanut...  
2  "Delight" says it all  This is a confection that has been around a fe...  
3         Cough Medicine  If you are looking for the secret ingredient i...  
4            Great taffy  Great taffy at a great price.  There was a wid...

In [81]:
data.columns

Index(['Id', 'ProductId', 'UserId', 'ProfileName', 'HelpfulnessNumerator',
       'HelpfulnessDenominator', 'Score', 'Time', 'Summary', 'Text'],
      dtype='object')

In [82]:
data.drop(['Id','ProductId','UserId','ProfileName','HelpfulnessNumerator','HelpfulnessDenominator','Summary'],axis=1,inplace=True)

In [83]:
data.head()

Score        Time                                               Text
0      5  1303862400  I have bought several of the Vitality canned d...
1      1  1346976000  Product arrived labeled as Jumbo Salted Peanut...
2      4  1219017600  This is a confection that has been around a fe...
3      2  1307923200  If you are looking for the secret ingredient i...
4      5  1350777600  Great taffy at a great price.  There was a wid...

In [84]:
del data['Time']

In [85]:
data.head()

Score                                               Text
0      5  I have bought several of the Vitality canned d...
1      1  Product arrived labeled as Jumbo Salted Peanut...
2      4  This is a confection that has been around a fe...
3      2  If you are looking for the secret ingredient i...
4      5  Great taffy at a great price.  There was a wid...

In [86]:
for _ in range(250):
    print(_)
    data = data.sample(frac=1)
X = data['Text']
y = data['Score']

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249


In [87]:
y = str(y)
print('1')
y = data['Score']
print('1')
cv = CountVectorizer()
print('1')
cv.fit(X)
print('1')
X_cv = cv.transform(X)
print('1')
# y_cv = cv.transform(y)
print('1')
X_train,X_test,y_train,y_test = train_test_split(X_cv,y,test_size=0.25)
print('1')

1
1
1
1
1
1
1


In [88]:
X_cv[0].toarray()

array([[0, 0, 0, ..., 0, 0, 0]])

In [89]:
y = pd.Series(y)

In [90]:
y = data['Score']

In [91]:
from sklearn.linear_model import *
print('1')
clf_SGDClassifier = SGDClassifier()
print('1')
clf_SGDClassifier.fit(X_train,y_train)
print('1')
text = ["bad"]
print('1')
text = cv.transform(text)
print('1')
clf_SGDClassifier.predict(text)
print('1')
print(clf_SGDClassifier.score(X_test,y_test))
print('1')
print(clf_SGDClassifier.predict(text))
import pickle
print('1')
pickle.dump(clf_SGDClassifier,open('clf_SGDClassifier.pkl','wb'))

1
1
1
1
1
1
0.7427769255667985
1
[5]
1


In [92]:
from sklearn.metrics import f1_score

In [93]:
data['Score'].value_counts()

5    363122
4     80655
1     52268
3     42640
2     29769
Name: Score, dtype: int64

In [94]:
f1_score(y_test,clf_SGDClassifier.predict(X_test),average=None,labels=[4,3,2,1,5])

array([0.27990512, 0.35452023, 0.27627054, 0.67757714, 0.86485456])

In [95]:
five_start_lists = []
for x in data.index[data['Score'] == 5].tolist():
    five_start_lists.append(x)

In [96]:
five_start_lists[1]

213153

In [97]:
to_remove = np.random.choice(data[data['Score']==5].index,size=282872,replace=False)
data.drop(to_remove,inplace=True)

In [98]:
data['Score'].value_counts()

4    80655
5    80250
1    52268
3    42640
2    29769
Name: Score, dtype: int64

In [99]:
to_remove = np.random.choice(data[data['Score']==4].index,size=405,replace=False)
data.drop(to_remove,inplace=True)

In [100]:
data['Score'].value_counts()

5    80250
4    80250
1    52268
3    42640
2    29769
Name: Score, dtype: int64

In [101]:
to_remove = np.random.choice(data[data['Score']==1].index,size=18,replace=False)
data.drop(to_remove,inplace=True)

In [102]:
data['Score'].value_counts()

5    80250
4    80250
1    52250
3    42640
2    29769
Name: Score, dtype: int64

In [103]:
for _ in range(250):
    print(_)
    data = data.sample(frac=1)
X = data['Text']
y = data['Score']
y = str(y)
print('1')
y = data['Score']
print('1')
cv = CountVectorizer()
print('1')
cv.fit(X)
print('1')
X_cv = cv.transform(X)
print('1')
# y_cv = cv.transform(y)
print('1')
X_train,X_test,y_train,y_test = train_test_split(X_cv,y,test_size=0.25)
print('1')
from sklearn.linear_model import *
print('1')
clf_SGDClassifier = SGDClassifier()
print('1')
clf_SGDClassifier.fit(X_train,y_train)
print('1')
text = ["bad food"]
print('1')
text = cv.transform(text)
print('1')
clf_SGDClassifier.predict(text)
print('1')
print(clf_SGDClassifier.score(X_test,y_test))
print('1')
print(clf_SGDClassifier.predict(text))
import pickle
print('1')
pickle.dump(clf_SGDClassifier,open('clf_SGDClassifier.pkl','wb'))

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
1
1
1
1
1
1
1
1
1
1
1
1
1
0.6067891709917239
1
[1]
1


In [104]:
text = ["worst food"]
print('1')
text = cv.transform(text)

1


In [105]:
clf_SGDClassifier.predict(text)

array([1])

In [106]:
len(data)

285159

In [107]:
f1_score(y_test,clf_SGDClassifier.predict(X_test),average=None,labels=[4,3,2,1,5])

array([0.55609519, 0.44414124, 0.34753163, 0.71406297, 0.7057386 ])

In [109]:
text = ["best food I have ever ate"]
print('1')
text = cv.transform(text)
clf_SGDClassifier.predict(text)

1


array([5])

In [111]:
import pickle
pickle.dump(cv,open('cv.pkl','wb'))

In [112]:
!ls

'archive (44).zip'	 cv.pkl        main.ipynb
 clf_SGDClassifier.pkl	 final.ipynb   Reviews.csv


In [114]:
text = ["foods getting bad smell",'best food']
text = cv.transform(text)
clf_SGDClassifier.predict(text)

array([1, 5])